/*
 * RECURSOS | Banco de 1.000 palabras
 * Diseño: Arley Zarate
 * Edite o agregue palabras separadas por comas.
 * Mantenga las comillas invertidas de inicio y cierre.
 * Se carga con <script src="palabras.js"> sin servidor local.
 */
window.RECURSOS_PALABRAS = `
ingeniería,Smart3D,AutoCAD,electricidad,Excel,programación,web,material,planificación,redacción,Colombia,dibujo,emprendimiento,YouTube,automatismo,proyecto,SP3D,CAD,
eléctrico,hojaelectrónica,informática,sitio,materialidad,programacióncronograma,ortografía,Bogotá,ilustración,comercio,vídeo,adaptabilidad,disciplina,SmartSketch,DWG,eléctrica,libro,algoritmo,
página,aceroestructural,cronograma,gramática,Cali,boceto,comercioelectrónico,video,abstracción,industria,Intergraph,DXF,electrotecnia,hojas,instrucción,portada,aceroinoxidable,hito,
puntuación,Chía,croquis,venta,tutorial,acumulación,infraestructura,Hexagon,SAT,electromecánica,cálculo,sentencia,inicio,galvanizado,fase,acentuación,Cundinamarca,esquema-diagrama,
ventas,transmisión,análisis,planta,modelado,DGN,subestación,fórmula,compilación,index,aleación,etapa,tilde,Valle,representación,vendedor,canal,arquitectura,
instalación,geometría,IFC,transformador,formulación,interpretación,navegación,fundición,actividad,mayúscula,Cauca,visualización,comprador,suscriptor,autenticación,montaje,entidad,LISP,
tablero,función,intérprete,buscador,hierro,tarea,minúscula,Antioquia,croquizado,consumidor,audiencia,autorización,construcción,objeto,AutoLISP,interruptor,UNICAR,compilador,
enlace,inoxidable,subtarea,sintaxis,Santander,esquemático,usuario,búsquedaSEO,autenticidad,operación,pieza,VisualLISP,seccionador,UNICHAR,ejecución,hiperenlace,aluminioanodizado,prioridad,
semántica,Meta,perspectiva3d,visitante,SEO,balance,mantenimiento,parte,macro,contactor,CONCAT,ejecutable,vínculo,cobreestañado,criticidad,léxico,Casanare,tridimensional,
público,títuloSEO,comportamiento,inspección,sólido,rutina,relé,CONCATENAR,aplicación,ancla,polímero,avance,vocabulario,Tolima,bidimensional,mercado,descripciónSEO,consistencia,
control,superficie,script,fusible,UNIRCADENAS,software,encabezado,plástico,seguimiento,terminología,Boyacá,secciónlongitudinal,producto,etiquetaSEO,continuidad,seguridad,vértice,automatización,
disyuntor,TEXTO,hardware,piepágina,polietileno,desempeño,tecnicismo,Huila,seccióntransversal,servicio,palabra-clave,conversión,calidad,arista,parametrización,protección,TEXTOUNIR,firmware,
sección,polipropileno,productividad,definición,Nariño,detalleconstructivo,artículo,miniatura,coordinación,norma,cara,parámetro,sobretensión,SI,sistemaoperativo,contenido,poliestireno,eficienciaoperativa,
concepto,Caribe,fachada,mercancía,clip,cobertura,estándar,curva,variable,sobrecorriente,SI.ERROR,Windows,tarjeta,poliamida,objetivo,significado,Pacífico,planta-general,
abastecimiento,corto,creatividad,criterio,arco,constante,cortocircuito,BUSCARV,Linux,panel,nylon,sinónimo,Orinoquía,planta-detalle,promoción,episodio,depuracióncontrol,especificación,
círculo,argumento,falla,BUSCARX,Android,modal,teflón,indicador,antónimo,Amazonía,plantaeléctrica,publicidad,grabar,descubrimiento,alcance,elipse,aislamiento,ÍNDICE,
iOS,ventanaemer-gente,poliacetal,KPI,concordancia,Andes,planimetría,identidad,grabaciónpantalla,disponibilidadlocal,polígono,expresión,aislante,COINCIDIR,navegador,desplegable,PVCrígido,presupuesto,
coherencia,cordillera,isometría,marca,capturapantalla,diversidad,diseño,segmento,condición,conductor,FILTRAR,archivo,PVCflexible,costo,cohesión,sabana,axonometría,logotipo,
narración,durabilidad,dimensionamiento,polilínea,bucle,conductividad,ORDENAR,directorio,deslizador,elastómero,precio,precisión,alzadofrontal,slogan,locución,escalabilidad,capacidad,trayectoria,
iteración,resistividad,ÚNICOS,carpeta,botón,caucho,tarifa,claridad,llanura,alzadoposterior,lema,voz,especificidad,rendimiento,eje,vector,resistividadtérmica,CONTAR,
ruta,enlaceinterno,goma,cotización,concisión,altiplano,alzadolateral,campaña,audio,exhaustividad,eficiencia,punto,escalar,cobre,CONTARA,extensión,enlaceexterno,silicona,
compra,brevedad,montaña,proyecciónortogonal,comunicación,micrófono,factibilidad,proceso,nodo,ángulo,aluminio,SUMA,nombre,URL,resina,adquisición,redundancia,colina,
despiece,propuesta,música,flexibilidad,procedimiento,origen,grados,acero,PROMEDIO,extensiónarchivo,dirección,epoxi,suministro,repetición,ladera,ensamblaje,valor,sonido,
fluidez,metodología,destino,radianes,MAX,acceso,dominio,epóxico,logística,repetitivo,pendiente,explosión,diferenciación,pista,funcionalidad,sistema,tangente,cobrizado,
MIN,lectura,subdominio,poliuretano,transporte,ambigüedad,terreno,componentes,atractivo,audiovisual,funcional,requerimiento,cartesiano,seno,recubrimiento,REDONDEAR,escritura,alojamiento,
policarbonato,inventario,estructura,suelo,solapamiento,exhibición,secuencia,frecuencia,revisión,global,coseno,blindaje,ENTERO,guardado,hosting,acrílico,existencia,oración,
subsuelo,superposición,vitrina,generación,aprobación,local,vértices,pantalla,IZQUIERDA,almacenamiento,servidor,metacrilato,disponibilidad,frase,subsuperficie,intersecciones,mostrador,posproducción,
gestión,actualización,personalizado,polilíneas,armadura,DERECHA,repositorio,localhost,fibra,necesidad,enunciado,roca,puntoscontrol,estantería,ediciónvideo,innovación,versión,posición,
hatch,malla,EXTRAE,recursos,vidrio,pedido,inciso,geología,cotadealtura,estante,fotograma-chave,interoperabilidad,trazabilidad,desplazamiento,sombreado,conexión,LARGO,desarrollo,
offline,fibraóptica,solicitud,apartado,geotecnia,texturizado,nivel,transiciónvideo,inventiva,entregable,rotación,achurado,equipotencialización,SUSTITUI,código,fibradecarbono,proveedor,numeral,
topografía,vista360,exhibidor,jerarquización,documentación,traslación,relleno,equipotencial,REEMPLAZAR,fuente,internet,compuesto,contratista,viñeta,cartografía,render,distribuciónproducto,subtítulo,
legibilidadvisual,memoria,escalado,línea,tierra,LIMPIAR,editor,intranet,laminado,cliente,enumeración,mapa,renderizado,organizaciónproducto,subtitulado,optimizaciónlocal,plano,simetría,
trazado,puestaatierra,ESPACIOS,depurador,madera,responsable,listado,coordenadas,fotorrealismo,visibilidad,doblaje,organizaciónweb,esquema,espejo,grosor,aterrizaje,CARACTER,depuración,
remoto,maderacontrachapada,supervisor,georreferenciación,hiperrealismo,accesovisual,descripciónvisual,personalización,referencia,matriz,plumilla,electrodo,prueba,caché,MDF,coordinador,legibilidad,geodesia,
composición,experienciausuario,guion,procesamientotexto,detalle,copia,escala,varilla,test,almacenamientoLocal,aglomerado,director,datum,encuadre,recorrido-cliente,storyboard,productividadpersonal,conjunto,
pegado,factor,triada,TRANSPONER,validación,navegadorweb,cartón,diseñador,transcripción,proyeccióncartográfica,ángulo-cámara,punto-venta,escaleta,puntualidad,componente,duplicado,proporción,jabalina,
columna,implementación,compatibilidad,papel,dibujante,digitación,latitud,panorámica,movilidad,apertura,recuperación,elemento,selección,formato,electrodovertical,fila,despliegue,responsivo,
tela,proyectista,corrección,longitud,retrato,portabilidad,introducción,reutilización,accesorio,filtro,presentación,pozotierra,rango,distribución,adaptación,lona,ingeniero,normalización,
este,paisaje,modularidad,explicación,sencillez,búsqueda,espacio,pozo,tableta,cuero,técnico,estandarización,norte,fondoimagen,plegado,pasoapaso,sincronización,soporte,
propiedad,modelo,inspeccionable,referenciaabsoluta,evolutivo,móvil,vinilo,operario,criterioeditorial,altitud,primerplano,desplegado,demostración,síntesisautomática,anclaje,atributo,registrador,referenciarelativa,
prototipo,escritorio,textil,trabajador,edición,cota,segundoplano,compuerta,ejemplo-resuelto,sistematización,cimentación,característica,viewport,registro,porcentaje,monitor,neopreno,administrador,
elevaciónterreno,profundidadcampo,tapa,solución,tecnología,pedestal,categoría,ventana,cámara,subtotal,lanzamiento,espuma,gestor,textoorganizado,curva-nivel,desenfoque,abatible,problema,
transformacióndigital,plataforma,familia,gráfica,canaleta,total,resolución,corcho,creador,polígonozona,exposición,error,usabilidad,pasarela,clase,impresión,bandeja,totalgeneral,
píxel,pintura,autor,parcela,contrasteimagen,cierre,utilidad,escalera,instancia,trazador,portacables,interfaz,densidad,organización,sangría,predio,iluminación,bisagra,
solucióntécnica,versatilidad,baranda,catálogo,ploteo,cableway,pie,tipografía,esmalte,clasificación,continuación,lote,luz,mecanismo,resultado,velocidadvisual,cubierta,plantilla,
ploteador,canalización,celdaactiva,terminal,imprimación,carpetaarchivos,salto,natural,articulación,recomendación,virtualización,cerramiento,librería,PDF,ductería,celdaformato,consola,letra,
anticorrosivo,estructuraarchivos,espaciado,propiedadindustrial,artificial,seguro,visualizacióninteractiva,biblioteca,exportación,ductobanco,numeración,comando,barniz,nomenclatura,párrafojustificado,focos,manija,consulta,
precisiónnumérica,señalización,entorno,importación,banco,consecutivo,palabra,acabado,nombrearchivo,alineaciónizquierda,zona,difusa,asa,pregunta,prevenciónfallas,demarcación,sesión,inserción,
enterrado,identificador,comandos,párrafo,pulido,etiquetaarchivo,alineaciónderecha,área,sombras,agarradera,respuestaaprendizaje,orientaciónobjetos,levantamiento,referenciaexterna,aéreo,shell,título,satinado,
metadatos,justificación,sector,perspectivaatmosférica,agarre,comentarioforo,retroalimentación,medición,permiso,bloque,subterráneo,PowerShell,mate,descripción,cursiva,región,paletacolor,rodamiento,
foro,verificabilidad,replanteo,bloqueo,atributobloque,zanja,batch,hipervínculo,brillante,finalidad,negrita,localidad,armonía,rueda,debate,trazable,coordenada,desbloqueo,
definicionbloque,fórmulaestructurada,automatizado,animación,rugoso,propósito,subrayado,municipio,cromática,neumático,comunidad,digitalización,elevación,bloqueanidado,arena,tabladinámica,manejador,transición,
liso,intención,resaltado,distrito,saturación,llanta,discusión,digitalizaciónplanos,orientación,ocultación,unidad,gravilla,gráficodinámico,evento,transformación,títulos,departamento,matiz,
aro,publicación,sincronizaciónarchivos,milímetro,concreto,segmentador,manejadoreventos,estriado,contexto,subtítulos,país,tono,rin,compartir,administraciónarchivos,vertical,centímetro,tuboconduit,
escucha,perforado,antecedente,resumen,territorio,intensidad,radio-bicicleta,enlacevideo,controlversiones,horizontal,metro,PVC,bordeexterno,interacción,color,ranurado,revisiónfinal,síntesis,
vecindario,luminosidad,pedal,enlacepublicación,bibliotecadigital,alineación,transparencia,pulgada,IMC,bordecelda
`;
